name: cpu-snn-glm-simulator

channels:
    - pytorch
    - pyg
    - defaults
    - conda-forge

dependencies:
        - pip
        - python
        - pytorch=1.13
        - cpuonly
        - pyg
        - pip:
          - -r requirements.txt
