[tool.poetry]
name = "snn-glm-simulator"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "snn_glm_simulator"}]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.21.4"
matplotlib = "^3.5.0"
tqdm = "^4.62.3"
scipy = "^1.7.3"
seaborn = "^0.11.2"
torch_geometric = {version = "^2.2.0", source="torch_geometric"}
torch_sparse = {version = "^0.6.15", source="torch_geometric"}
torch_scatter = {version = "^2.0.9", source="torch_geometric"}
torch_cluster = {version = "^1.6.0", source="torch_geometric"}
torch_spline_conv = {version = "^1.2.1", source="torch_geometric"}
torch = {version = "^1.13.0", source="pytorch"}
ipython = "^8.8.0"
pytest-lazy-fixture = "^0.6.3"
pytest = "^7.2.0"

[[tool.poetry.source]]
name = "torch_geometric"
url = "https://data.pyg.org/whl/torch-1.13.0+cpu.html"
secondary = true

[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"
secondary = true


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
